language: r
sudo: required
r_binary_packages:
  - testthat
  - xml
  - base64enc
  - rmarkdown
  - stringi
  - jsonlite
  - httpuv
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
after_failure:
  - ./travis-tool.sh dump_logs
r_packages:
  - PKI
warnings_are_errors: true
