# Site settings
title: rapier
email: rapier@trestletech.com
description: > # this means to ignore newlines until "baseurl:"
  An R package that generates a web API from the R code you already have.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rapier.trestletech.com" # the base hostname & protocol for your site
twitter_username: trestleJeff
github_username:  trestletech
rapier_url: http://rapier.tres.tl/append

# Build settings
markdown: kramdown
