# Site settings
title: plumber
email: 
description: > # this means to ignore newlines until "baseurl:"
  An R package that generates a web API from the R code you already have.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://plumber.trestletech.com" # the base hostname & protocol for your site
twitter_username: trestleJeff
github_username:  trestletech/plumber
plumber_url: https://demo.rplumber.io
disqus_id: trestle-plumbr
#plumbr_url: http://localhost:8000

# Build settings
markdown: kramdown
