version: '2'
services:
  append: 
    build: ../examples/01-append/
    volumes:
     - ../examples:/examples
    restart: always
  sessions:
    build: ../examples/06-sessions/
    volumes:
     - ../examples:/examples
    restart: always
  mailgun:
    build: ../examples/07-mailgun/
    volumes:
     - ../examples:/examples
    restart: always
  nginx:
    image: nginx:1.9
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
     - append
     - sessions
     - mailgun
